version: '2.1'
services:

  database:
    extends:
      file: common.yml
      service: database

  nzedb:
    extends:
      file: common.yml
      service: nzedb
    links:
      - database
      - redis
    depends_on:
      - database
        #condition: service_healthy
      - redis
        #condition: service_started

  adminer:
    extends:
      file: common.yml
      service: adminer
    links:
      - database:db
    depends_on:
      - database
        # condition: service_healthy

  redis:
    extends:
      file: common.yml
      service: redis


  phpmyadmin:
    extends:
      file: common.yml
      service: phpmyadmin
    links:
      - database:db
    depends_on:
      - database
        # condition: service_healthy